name: Run Tests

on: [push, pull_request]

jobs:
  check_tests:
    name: Check for test scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if test scripts exist
        run: |
            if [ ! -f "./tests/test_script.sh" ]; then
            echo "Testne skripte niso bile najdene" > napaka.txt
            exit 1
            else
            > napaka.txt
            fi
        continue-on-error: true

      - name: Upload error file
        uses: actions/upload-artifact@v4
        with:
          name: error-file
          path: napaka.txt

  run_tests:
    name: Prepare environment and run tests
    runs-on: ubuntu-latest
    needs: check_tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download error file
        uses: actions/download-artifact@v4
        with:
          name: error-file
          path: .

      - name: Check for errors
        run: |
            if [ -s napaka.txt ]; then
                cat napaka.txt
                > napaka.txt
                exit 1
            else
                echo "Vse stima"
            fi
      - name: Install dependencies
        run: sudo apt-get install -y g++ make

      - name: Compile the code
        run: make

      - name: Run tests
        run: ./tests/test_script.sh