name: Run Tests

on: [push]

jobs:
  check_tests: #preveri ce testi obstajajo
    name: Check for test scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository #checkaout trenutni repo
        uses: actions/checkout@v2
      #pogleda ce obstajajo
      - name: Check if test scripts exist
        run: |
            if [ ! -f "./tests/test_script.sh" ]; then
                echo "Testne skripte niso ble najdene" > napaka.txt
                exit 1
            else
                > napaka.txt
            fi
        continue-on-error: true
      #dal sem da se u usakem primeru nalozi napaka.txt pol pa sam preveri ce nima vsebine je use ok drgace pa vsebuje napako
      - name: Upload error file
        uses: actions/upload-artifact@v4
        with:
          name: error-file
          path: napaka.txt

  run_tests: #zalaufa teste
    name: Prepare environment and run tests
    runs-on: ubuntu-latest
    needs: check_tests
    steps:
      - name: Checkout repository #spet checkout repo
        uses: actions/checkout@v2

      - name: Download error file #prek artefaktov nalozi possible errorje
        uses: actions/download-artifact@v4
        with:
          name: error-file
          path: .
      #tu sam preveri ce ima napak.txt vsebino alpa je prazna
      - name: Check for errors
        run: |
            if [ -s napaka.txt ]; then
                cat napaka.txt
                > napaka.txt
                exit 1
            else
                echo "Vse stima"
            fi
      - name: Install dependencies
        run: sudo apt-get install -y g++ make
      #intalla g++ za compilanje pa nardi skripto executable
      - name: Make test script executable
        run: chmod +x ./tests/test_script.sh

      - name: Compile the code
        run: make
      #zalaufa teste
      - name: Run tests
        run: ./tests/test_script.sh